---
- name: clone repo
  git:
    repo: "{{ github_base }}{{ github_user }}/dotfiles.git"
    dest: $HOME/.dotfiles
    accept_hostkey: yes
  register: clone_repo

- name: initialize submodules
  shell: git submodule init
  args:
    chdir: $HOME/.dotfiles
  when: clone_repo.changed

- name: updating submodules
  shell: git submodule update
  args:
    chdir: $HOME/.dotfiles
  when: clone_repo.changed

- name: load dotfiles 
  shell: $HOME/.dotfiles/setup
  when: clone_repo.changed

