---
- name: install sudo
  pacman:
    name: sudo

- name: configure sudo
  copy:
    src: sudoers
    dest: /etc/sudoers
    validate: /usr/sbin/visudo -cf %s

- name: "create user {{ username }}"
  user:
    name: "{{ username }}"
    groups: wheel
  register: user_created

- name: create .ssh dir
  file:
    path: $HOME/.ssh
    state: directory
  become_user: "{{ username }}"

- name: copy authorized keys
  copy:
    src: "{{ ssh_pubkey }}.pubkey"
    dest: $HOME/.ssh/authorized_keys
  become_user: "{{ username }}"

- name: "set {{ username }} shell to zsh"
  user:
    name: "{{ username }}"
    shell: /bin/zsh

- name: install pexpect
  pacman:
    name: python-pexpect

- name: "set {{ username }} password"
  expect:
    command: passwd
    responses:
      New password.*: "{{ user_password }}"
      Retype new password.*: "{{ user_password }}"
  when: user_created.changed
